# Generated by Django 3.1.3 on 2020-11-21 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='0', max_length=200), null=True, size=None)),
                ('moodDateList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='0', max_length=200), null=True, size=None)),
            ],
        ),
    ]
