# Generated by Django 3.1.3 on 2020-11-22 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, default='NULL', max_length=200)),
                ('date', models.CharField(blank=True, default='NULL', max_length=200)),
                ('log', models.CharField(blank=True, default='NULL', max_length=10000)),
                ('analysis', models.CharField(blank=True, default='NULL', max_length=10000)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
