# Generated by Django 3.1.3 on 2020-11-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='goalStatus',
            field=models.CharField(blank=True, default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='date',
            field=models.CharField(blank=True, default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='mood',
            field=models.CharField(blank=True, default='NULL', max_length=500),
        ),
    ]
