# Generated by Django 3.1.3 on 2020-11-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='analysis',
            field=models.CharField(blank=True, default='NULL', max_length=10000),
        ),
        migrations.AddField(
            model_name='userlogs',
            name='log',
            field=models.CharField(blank=True, default='NULL', max_length=10000),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='moodDateList',
            field=models.CharField(blank=True, default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='moodList',
            field=models.CharField(blank=True, default='NULL', max_length=200),
        ),
    ]
