# Generated by Django 3.1.3 on 2020-11-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogs', '0002_auto_20201121_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogs',
            old_name='moodDateList',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='userlogs',
            old_name='moodList',
            new_name='mood',
        ),
    ]
