# Generated by Django 3.1.3 on 2020-11-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('endTime', models.CharField(max_length=100)),
                ('prodGoal', models.CharField(max_length=100)),
            ],
        ),
    ]
