# Generated by Django 3.1.3 on 2020-11-21 09:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None)),
                ('startTime', models.CharField(max_length=100)),
                ('endTime', models.CharField(max_length=100)),
                ('prodGoal', models.CharField(max_length=100)),
            ],
        ),
    ]
