<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-22 04:20

from django.conf import settings
=======
# Generated by Django 3.1.3 on 2020-11-21 09:53

>>>>>>> 3dc5d4e... google api
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='NULL', max_length=200), null=True, size=None)),
                ('startTime', models.CharField(max_length=100, null=True)),
                ('endTime', models.CharField(max_length=100, null=True)),
                ('prodGoal', models.FloatField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
