# Generated by Django 3.1.3 on 2020-11-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201121_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activities',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='userprofile.activities'),
        ),
    ]
