# Generated by Django 3.1.3 on 2020-11-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201121_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='moodDateList',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='moodList',
        ),
    ]
