# Generated by Django 3.1.3 on 2020-11-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201121_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='prodGoal',
            field=models.FloatField(null=True),
        ),
    ]
