# Generated by Django 3.1.3 on 2020-11-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201121_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activities',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
    ]
