# Generated by Django 3.1.3 on 2020-11-21 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20201121_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
    ]
