export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const STORE_USER_PROFILE = "STORE_USER_PROFILE";
export const CREATE_USER_PROFILE = "CREATE_USER_PROFILE";
export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE";
export const IS_PROFILE = "IS_PROFILE";
